### ISSUE TITLE
Support multiple files

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/tsd-check#14]
Sometimes the `index.test-d.ts` grows large and you would like to split it up. Would be nice if this was possible.

We could support some convention like picking up all the files in a `test-d` directory.

The directory path could be configurable through a property in package.json.

---

The current workaround is to just import the other files into `index.test-d.ts`:

```ts
import './test/merge';
```

We should document this. Note that it should not have an extension in the import path.

**Comment by BendingBender** [comment]
@SamVerschueren Do you already have an idea how you would do this? Just out of curiosity.
