### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/tsd-check#6]
I realize this is the TS compiler being slow but is there any way we could improve the performance?

```
~/dev/oss/write-json-file master*
❯ time ./node_modules/.bin/tsd-check
real         1.72
user         2.47
sys          0.12
```

It shouldn't take 2 seconds to check a simple test file.

**Comment by StarpTech** [comment]
I could reduce the time from ~`2291,5909` to ~`1469,8804ms` with the compiler option `skipLibCheck`: true`.

**Comment by StarpTech** [comment]
I could improve it further https://github.com/SamVerschueren/tsd-check/pull/8
